name: Build Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependancies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y build-essential
        sudo apt-get install -y libgtk-3-dev
        sudo apt-get install -y libsdl2-2.0-0
        sudo apt-get install -y libnotify4
        sudo apt-get install xvfb
        python -m pip install --upgrade pip
        pip install -r requirements_linux.txt

    - name: Lint with flake8
      run: |
        cd rustre
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        cd ..

    - name: Run test
      run: |
        pytest test --log-cli-level=INFO

    - name: Code coverage
      run: |
        pytest --cov=rustre
    
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github


