
name: Build Windows

on:
  push:
  release:
    types: [created]

jobs:
  build:
    name: Windows Build
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create the version file
      run: |
        cd rustre
        python createversion.py version.py
        cd ..

#    - name: Run test
#      run: |
#        pytest test --log-cli-level=INFO

    - name: Create the binary
      run: |
        cd install
        python createapp.py Windows --no-bundled
        cd ..

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: |
          ${{github.workspace}}/bin/*.exe
          ${{github.workspace}}/bin/dist/*.exe
          ${{github.workspace}}/*.exe

  upload_all:
    name: Upload if release
    needs: [build]
    runs-on: ubuntu-22.04
    if: github.event_name == 'release' && github.event.action == 'created'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist
      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload to releases
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "dist/bin/dist/*.exe;dist/bin/dist/*.zip"
          tags: true
          draft: true
          verbose: true
