name: test-linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependancies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test
      run: |
        pytest test --log-cli-level=INFO

    - name: Code coverage
      run: |
        pytest --cov=rustre --cov-report xml
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.xml


